#build
FROM node:24-alpine AS builder
WORKDIR /app

COPY package*.json .
RUN npm  ci

COPY prisma ./prisma
RUN npx prisma generate

COPY . .
RUN npm run build

#runner
FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/src/generated ./dist/generated

EXPOSE 3000
CMD [ "node","dist/index.js"]